name: "Build and Test"

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/Build.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Test
        run: |
          sbt compile
          sbt test
