name: "Publish"

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/Publish.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ushibutatory-pj-euler-scala"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "src/EulerProject"
        env:
          HD_APPLICATION_SECRET: ${{ secrets.PLAY_APP_SECRET }} # for Play Application Secret
